version: '3'
services:
  api: 
      build: .
      ports:
        - 3000:3000
      volumes:
        - .:/usr/src/app
      command: air main.go -b 0.0.0.0

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  

